// Respect Do Not Track / Global Privacy Control. If the visitor has a privacy
// signal set, opt them out of analytics entirely: setting no_onload before
// /vendor/goatcounter-count.js runs (it is deferred and appears after this
// file, so this executes first) stops the pageview beacon and click-event
// binding without modifying the vendored script. See count.js (the
// `if (!goatcounter.no_onload)` guard).
(function () {
    var dnt = navigator.doNotTrack || window.doNotTrack || navigator.msDoNotTrack;
    if (navigator.globalPrivacyControl === true || dnt === '1' || dnt === 'yes') {
        window.goatcounter = window.goatcounter || {};
        window.goatcounter.no_onload = true;
    }
})();

function debounce(func, wait) {
    let timeout;
    return function executedFunction(...args) {
        const later = () => {
            clearTimeout(timeout);
            func(...args);
        };
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
    };
}

const domCache = {
    searchInput: null,
    categoryHeaders: null,
    cards: null
};

function sanitize(str) {
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
}

document.addEventListener('DOMContentLoaded', function() {
    document.body.classList.add('js-enabled');

    domCache.searchInput = document.getElementById('searchInput');
    domCache.categoryHeaders = document.querySelectorAll('.category-section h3');
    domCache.cards = document.querySelectorAll('.resource-card');

    initThemeToggle();
    initSearchSuggestions();
    initShareButtons();

    document.querySelectorAll('a[target="_blank"]').forEach(link => {
        const rel = (link.getAttribute('rel') || '').split(' ').filter(Boolean);
        if (!rel.includes('noopener')) rel.push('noopener');
        if (!rel.includes('noreferrer')) rel.push('noreferrer');
        link.setAttribute('rel', rel.join(' '));
    });

    const hamburger = document.querySelector('.hamburger');
    if (hamburger) {
        hamburger.addEventListener('click', function () {
            const header = this.closest('.header-content');
            const isOpen = document.body.classList.toggle('nav-open');
            if (header) header.classList.toggle('nav-open', isOpen);
            this.setAttribute('aria-expanded', String(isOpen));
            this.textContent = isOpen ? '✕' : '☰';
        });
    }

    initDropdownNav();

    // Site-wide search affordance. Adding a search link directly to every
    // page's hardcoded <nav> would require touching ~30 HTML files; instead
    // we inject one <li> into the top-level nav ul at runtime. The actual
    // search UI lives at /search.html (Pagefind-backed).
    injectSearchLink();

    // Measure the sticky header and expose its real height as --header-height
    // so anchor jumps clear it. Runs after injectSearchLink() since that
    // mutates the nav (and thus the header's height).
    initHeaderHeightVar();

    // Add accessible label for search input
    if (domCache.searchInput && !document.querySelector('label[for="searchInput"]')) {
        const label = document.createElement('label');
        label.setAttribute('for', 'searchInput');
        label.className = 'visually-hidden';
        label.textContent = 'Search resources';
        domCache.searchInput.parentNode.insertBefore(label, domCache.searchInput);
    }
    
    // Add icons to resource cards
    addIconsToCards();

    // Load preview mapping (generated by tools/generate_previews.py) then add previews
    loadPreviewMap().then(() => {
        addPreviewImagesToCards();
    });

    // Tooltip on hover for resource cards with data-tooltip
    initTooltips();
    
    // Show All Articles button
    const showAllBtn = document.getElementById('showAllBtn');
    if (showAllBtn) {
        showAllBtn.addEventListener('click', () => {
            // Clear search input
            if (domCache.searchInput) {
                domCache.searchInput.value = '';
            }
            // Remove active state from all tag filters
            document.querySelectorAll('.filter-btn').forEach(btn => {
                btn.classList.remove('active');
            });
            // Show all cards
            const cards = document.querySelectorAll('.resource-card');
            cards.forEach(card => {
                getToggleTarget(card).style.display = '';
            });
            updateVisibleCount();
        });
    }

    // Search functionality with debounce for better performance
    if (domCache.searchInput) {
        const params = new URLSearchParams(window.location.search);
        const query = sanitize(params.get('q') || '');
        if (query) {
            domCache.searchInput.value = query;
            filterResources(query.toLowerCase());
        }

        // Support ?category= URL parameter for deep-linking from footer/nav
        const categoryParam = params.get('category');
        const validCategories = ['all', 'ctf', 'tool', 'certification', 'lab', 'ai-security', 'job', 'new'];
        if (categoryParam && !query && validCategories.includes(categoryParam)) {
            // Defer to allow DOM to fully settle (tag filters, card icons, etc.)
            setTimeout(function() {
                // Activate the matching filter button
                document.querySelectorAll('button[data-category]').forEach(function(b) {
                    b.classList.remove('active');
                    b.setAttribute('aria-pressed', 'false');
                });
                var btn = document.querySelector('button[data-category="' + categoryParam + '"]');
                if (btn) {
                    btn.classList.add('active');
                    btn.setAttribute('aria-pressed', 'true');
                }
                // Apply the filter
                if (categoryParam === 'all') {
                    document.querySelectorAll('.resource-card').forEach(function(card) {
                        getToggleTarget(card).style.display = '';
                    });
                } else if (categoryParam === 'new') {
                    filterByTagText('new');
                } else {
                    filterBySection(categoryParam);
                }
                updateVisibleCount();
            }, 50);
        }

        const debouncedSearch = debounce(function(e) {
            const searchTerm = e.target.value.toLowerCase();
            filterResources(searchTerm);
        }, 150);
        domCache.searchInput.addEventListener('input', debouncedSearch);
    }

    // Category filter buttons - direct attachment for better mobile support
    const categoryButtons = document.querySelectorAll('button[data-category]:not(.tag-filter)');
    categoryButtons.forEach(btn => {
        btn.addEventListener('click', function(e) {
            e.preventDefault();
            const category = this.dataset.category;
            
            // Remove active class from all category buttons
            document.querySelectorAll('button[data-category]:not(.tag-filter)').forEach(b => {
                b.classList.remove('active');
                b.setAttribute('aria-pressed', 'false');
            });
            
            // Add active class to clicked button
            this.classList.add('active');
            this.setAttribute('aria-pressed', 'true');
            
            // Clear search input
            if (domCache.searchInput) {
                domCache.searchInput.value = '';
            }
            
            // Filter by category
            if (category === 'all') {
                // Show all cards
                const cards = document.querySelectorAll('.resource-card');
                cards.forEach(card => {
                    getToggleTarget(card).style.display = '';
                });
            } else if (category === 'new') {
                // Filter by 'new' tag
                filterByTagText('new');
            } else {
                // Filter by section (ctf, tool, certification, lab, ai-security, job)
                filterBySection(category);
            }
            
            updateVisibleCount();
        });
    });

    // Category collapse/expand - use event delegation
    const mainContent = document.getElementById('main-content');
    if (mainContent) {
        // Initialize ARIA attributes on category headers
        document.querySelectorAll('.category-section h3').forEach(header => {
            header.setAttribute('role', 'button');
            header.setAttribute('tabindex', '0');
            const isCollapsed = header.parentElement.classList.contains('collapsed');
            header.setAttribute('aria-expanded', String(!isCollapsed));
        });

        mainContent.addEventListener('click', function(e) {
            const header = e.target.closest('.category-section h3');
            if (header && header.parentElement.classList.contains('category-section')) {
                header.parentElement.classList.toggle('collapsed');
                const isCollapsed = header.parentElement.classList.contains('collapsed');
                header.setAttribute('aria-expanded', String(!isCollapsed));
            }
        });

        // Keyboard support: Enter/Space to toggle
        mainContent.addEventListener('keydown', function(e) {
            if (e.key === 'Enter' || e.key === ' ') {
                const header = e.target.closest('.category-section h3');
                if (header && header.parentElement.classList.contains('category-section')) {
                    e.preventDefault();
                    header.click();
                }
            }
        });
    }

    // Card click functionality is now handled via HTML <a> wrapper

    // Smooth scrolling for anchor links
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function(e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({
                    behavior: 'smooth',
                    block: 'start'
                });
            }
        });
    });
    // Initialize dynamic tag filters and visible count on load
    if (typeof generateSourceFilters === 'function') generateSourceFilters();
    if (typeof generateTagFilters === 'function') generateTagFilters();
    if (typeof updateVisibleCount === 'function') updateVisibleCount();
});

// Generate tag filter buttons dynamically from tags on the page
function generateTagFilters() {
    const container = document.getElementById('allTagsContainer');
    if (!container) return;
    container.innerHTML = '';

    // Count occurrences of each tag text
    const tagNodes = Array.from(document.querySelectorAll('.resource-card .tag'));
    const counts = {};
    tagNodes.forEach(t => {
        const txt = t.textContent.trim();
        if (!txt) return;
        counts[txt] = (counts[txt] || 0) + 1;
    });

    // Sort tags by frequency (descending), tiebreak alphabetically
    const sortedTags = Object.keys(counts).sort((a, b) => {
        const diff = counts[b] - counts[a];
        return diff !== 0 ? diff : a.localeCompare(b);
    });

    // Track expanded state
    let isExpanded = false;
    const TOP_N = 20;

    // Function to render tags (top N or all)
    const renderTags = (showAll = false) => {
        // Clear existing buttons but keep toggle button if visible
        Array.from(container.querySelectorAll('.tag-filter')).forEach(btn => btn.remove());
        Array.from(container.querySelectorAll('.toggle-tags-btn')).forEach(btn => btn.remove());

        const tagsToRender = showAll ? sortedTags : sortedTags.slice(0, TOP_N);

        tagsToRender.forEach(tagText => {
            const btn = document.createElement('button');
            btn.className = 'filter-btn tag-filter';
            btn.dataset.tag = tagText;
            btn.textContent = `${tagText} (${counts[tagText]})`;
            btn.title = `${counts[tagText]} resources`;
            btn.addEventListener('click', function() {
                // clear other active buttons
                document.querySelectorAll('.filter-btn').forEach(b => {
                    b.classList.remove('active');
                    b.setAttribute('aria-pressed', 'false');
                });
                document.querySelectorAll('.tag-filter').forEach(b => {
                    b.classList.remove('active');
                    b.setAttribute('aria-pressed', 'false');
                });
                this.classList.add('active');
                this.setAttribute('aria-pressed', 'true');
                filterByTagText(tagText);
            });
            container.appendChild(btn);
        });

        // Add toggle button if there are more tags than TOP_N
        if (sortedTags.length > TOP_N) {
            const toggleBtn = document.createElement('button');
            toggleBtn.className = 'filter-btn toggle-tags-btn';
            toggleBtn.textContent = showAll ? `Show fewer tags (${TOP_N})` : `Show all tags (${sortedTags.length})`;
            toggleBtn.addEventListener('click', function() {
                isExpanded = !isExpanded;
                renderTags(isExpanded);
            });
            container.appendChild(toggleBtn);
        }
    };

    // Initial render: top N tags only
    renderTags(false);
}

// Friendly display names for news source slugs
var SOURCE_DISPLAY_NAMES = {
    "aws-security-blog": "AWS Security",
    "google-cloud-blog": "Google Cloud",
    "microsoft-msrc": "Microsoft MSRC",
    "cloudflare-blog": "Cloudflare",
    "sans-isc": "SANS ISC",
    "bleepingcomputer": "BleepingComputer",
    "thehackernews": "The Hacker News",
    "securityweek": "SecurityWeek",
    "krebsonsecurity": "KrebsOnSecurity",
    "darkreading": "Dark Reading",
    "helpnetsecurity": "Help Net Security",
    "infosecurity-magazine": "Infosecurity Mag",
    "securityaffairs": "Security Affairs",
    "schneier": "Schneier",
    "theregister": "The Register",
    "google-online-security": "Google Security",
    "crowdstrike": "CrowdStrike",
    "unit42": "Unit 42",
    "cisa": "CISA"
};

// Generate source filter buttons dynamically from data-source attributes
function generateSourceFilters() {
    var container = document.getElementById('sourceFiltersContainer');
    if (!container) return;
    container.innerHTML = '';

    // Count articles per source
    var cards = document.querySelectorAll('.resource-card[data-source]');
    var counts = {};
    cards.forEach(function (card) {
        var src = card.dataset.source;
        if (src) counts[src] = (counts[src] || 0) + 1;
    });

    // Sort by count descending, then alphabetically
    var sorted = Object.keys(counts).sort(function (a, b) {
        var diff = counts[b] - counts[a];
        return diff !== 0 ? diff : a.localeCompare(b);
    });

    if (sorted.length === 0) return;

    var label = document.createElement('h4');
    label.textContent = 'Filter by Source:';
    label.className = 'source-filter-label';   // was style.cssText, which CSP blocks
    container.appendChild(label);

    sorted.forEach(function (slug) {
        var btn = document.createElement('button');
        btn.className = 'filter-btn source-filter';
        btn.dataset.source = slug;
        var name = SOURCE_DISPLAY_NAMES[slug] || slug;
        btn.textContent = name + ' (' + counts[slug] + ')';
        btn.title = counts[slug] + ' articles from ' + name;
        btn.addEventListener('click', function () {
            // Clear all filter buttons (tags + sources)
            document.querySelectorAll('.filter-btn').forEach(function (b) {
                b.classList.remove('active');
                b.setAttribute('aria-pressed', 'false');
            });
            this.classList.add('active');
            this.setAttribute('aria-pressed', 'true');
            filterBySource(slug);
        });
        container.appendChild(btn);
    });
}

// Filter cards by data-source attribute
function filterBySource(slug) {
    var cards = document.querySelectorAll('.resource-card');
    cards.forEach(function (card) {
        getToggleTarget(card).style.display = card.dataset.source === slug ? '' : 'none';
    });
    if (typeof updateVisibleCount === 'function') updateVisibleCount();
}

let previewMap = {};

function loadPreviewMap() {
    // Bypass HTTP cache so fresh entries (added on every PR by the workflow)
    // are picked up without waiting for the browser's cache to expire.
    return fetch('preview-mapping.json', { cache: 'no-cache' })
        .then(resp => {
            if (!resp.ok) return {};
            return resp.json();
        })
        .then(json => {
            previewMap = json || {};
        })
        .catch(() => { previewMap = {}; });
}

// Filter cards by tag text (case-insensitive)
function filterByTagText(tagText) {
    const search = tagText.toLowerCase();
    const cards = document.querySelectorAll('.resource-card');
    cards.forEach(card => {
        const tags = Array.from(card.querySelectorAll('.tag')).map(t => t.textContent.toLowerCase()).join(' ');
        getToggleTarget(card).style.display = tags.includes(search) ? '' : 'none';
    });
    updateVisibleCount();
}

// Map category button values to their section IDs in resources.html
const categorySectionMap = {
    'ctf': 'ctf-challenges',
    'tool': 'security-tools',
    'certification': 'certifications',
    'lab': 'labs-training',
    'ai-security': 'ai-security',
    'job': 'job-search'
};

function filterBySection(category) {
    const sectionId = categorySectionMap[category];
    if (!sectionId) return;
    const cards = document.querySelectorAll('.resource-card');
    cards.forEach(card => {
        const section = card.closest('.category-section');
        const inSection = section && section.id === sectionId;
        getToggleTarget(card).style.display = inSection ? '' : 'none';
    });
    updateVisibleCount();
}

// news.html's article cards are rewritten from the RSS feeds every week by
// update-news.yml, so they cannot carry a hand-placed data-icon - anything
// added here would be dropped at the next refresh. The generator does stamp a
// stable data-category on each card, which is a far better signal than the
// padlock the keyword classifier below falls back to. These three values are
// news.html's alone; no other page uses them.
const CARD_CATEGORY_ICONS = {
    report: '\u{1F4F0}',
    vulnerability: '\u26A0\uFE0F',
    breach: '\u{1F6A8}'
};

function addIconsToCards() {
    // Opt-out for pages whose cards are deliberately text-only. The classifier
    // below keys off tags and title keywords and falls back to a generic
    // padlock when it cannot place a card, which is fine for the third-party
    // directory it was written for. On an index of our own topic pages nothing
    // matches, so every card renders the same glyph: 40 identical padlocks that
    // encode nothing and cost a row of height each. topics.html sets
    // data-no-card-icons on <main> for that reason.
    if (document.querySelector('[data-no-card-icons]')) return;

    const cards = document.querySelectorAll('.resource-card');
    
    cards.forEach(card => {
        // Skip if icon already exists or card has a banner/preview image
        if (card.querySelector('.resource-card-icon')) return;
        if (card.querySelector('.resource-preview')) return;
        
        const tags = Array.from(card.querySelectorAll('.tag')).map(tag => tag.textContent.toLowerCase());
        const title = card.querySelector('h3').textContent.toLowerCase();
        
        let icon = '🔐'; // default security icon
        let iconClass = '';

        // Helper: exact tag match (case-insensitive). Avoids substring false-positives
        // like "Daily" matching "ai" or "Chain" matching "ai".
        const tagEquals = (needle) => tags.some(tag => tag === needle);

        // Determine icon based on tags and content. Order matters - earlier matches win.
        //
        // An authored page names its own glyph and wins outright. The classifier
        // below was written for the third-party resource directory, where every
        // card carries a tag like "Tool" or "CTF"; on a page of our own prose
        // cards nothing matches and all of them render the same padlock. The fix
        // is not more title keywords - those guess, and drift the moment a
        // heading is reworded - it is letting the page say what it means.
        if (card.dataset.icon) {
            icon = card.dataset.icon;
        } else if (tagEquals('newsletter')) {
            icon = '📬';
            iconClass = 'newsletter';
        } else if (tagEquals('blog')) {
            icon = '✍️';
            iconClass = 'blog';
        } else if (tagEquals('podcast')) {
            icon = '🎙️';
            iconClass = 'podcast';
        } else if (tags.some(tag => tag.includes('ctf')) || title.includes('ctf') || title.includes('goat') || title.includes('vulnerable')) {
            icon = '🎯';
            iconClass = 'ctf';
        } else if (tags.some(tag => tag.includes('tool')) || tags.some(tag => tag.includes('cspm')) || tags.some(tag => tag.includes('cnapp'))) {
            icon = '🛠️';
            iconClass = 'tool';
        } else if (tags.some(tag => tag.includes('certification')) || title.includes('cert')) {
            icon = '🎓';
            iconClass = 'certification';
        } else if (tags.some(tag => tag.includes('lab') || tag.includes('hands-on') || tag.includes('training'))) {
            icon = '🧪';
            iconClass = 'lab';
        } else if (tags.some(tag => tag.includes('kubernetes') || tag.includes('k8s')) || title.includes('kubernetes')) {
            icon = '☸️';
            iconClass = 'kubernetes';
        } else if (tagEquals('ai') || tagEquals('ml') || tagEquals('ai-security') || tagEquals('ai security') || /\bai\b/.test(title)) {
            icon = '🤖';
            iconClass = 'ai';
        } else if (title.includes('aws')) {
            icon = '☁️';
            iconClass = 'tool';
        } else if (title.includes('azure')) {
            icon = '☁️';
            iconClass = 'tool';
        } else if (title.includes('gcp') || title.includes('google cloud')) {
            icon = '☁️';
            iconClass = 'tool';
        } else if (CARD_CATEGORY_ICONS[card.dataset.category]) {
            icon = CARD_CATEGORY_ICONS[card.dataset.category];
        }
        
        // Create icon element
        const iconDiv = document.createElement('div');
        iconDiv.className = `resource-card-icon ${iconClass}`.trim();
        iconDiv.textContent = icon;
        
        // Insert icon at the beginning of the card
        card.insertBefore(iconDiv, card.firstChild);
    });
}

// Insert a small preview screenshot for each resource card.
// Uses WordPress mShots service to generate a lightweight thumbnail.
function addPreviewImagesToCards() {
    const cards = document.querySelectorAll('.resource-card');

    cards.forEach(card => {
        // Skip if card marked as no-preview (e.g., index page category cards)
        if (card.hasAttribute('data-no-preview')) return;

        // avoid duplicating previews
        if (card.querySelector('.resource-preview')) return;

        const link = card.querySelector('h3 a');
        if (!link) return;

        const url = link.href;
        if (!url) return;

        // Skip cards with no local preview available - no third-party fallback.
        // (Avoids inserting an empty <img> that renders as a broken-image placeholder.)
        if (!previewMap[url]) return;

        const img = document.createElement('img');
        img.className = 'resource-preview';
        img.alt = `Preview of ${link.textContent.trim()}`;
        img.loading = 'lazy';
        img.referrerPolicy = 'no-referrer';
        img.decoding = 'async';
        // Set explicit dimensions to prevent layout shift
        img.width = 600;
        img.height = 160;

        img.src = previewMap[url];
        img.onerror = function() { img.remove(); };

        // Place the preview after any icon but before the title
        const icon = card.querySelector('.resource-card-icon');
        if (icon && icon.nextSibling) {
            card.insertBefore(img, icon.nextSibling);
        } else if (icon) {
            card.appendChild(img);
        } else {
            card.insertBefore(img, card.firstChild);
        }
    });
}

// Helper: get the element to show/hide for a given card.
// On news.html cards are wrapped in <a class="card-link">, on resources.html they are standalone.
function getToggleTarget(card) {
    const parent = card.parentElement;
    return (parent && parent.classList.contains('card-link')) ? parent : card;
}

function filterResources(searchTerm) {
    // Use cached cards or query if not available
    const cards = domCache.cards.length > 0 ? domCache.cards : document.querySelectorAll('.resource-card');
    
    // Use requestAnimationFrame for smoother rendering
    requestAnimationFrame(() => {
        cards.forEach(card => {
            const title = card.querySelector('h3')?.textContent.toLowerCase() || '';
            const paragraphs = Array.from(card.querySelectorAll('p')).map(p => p.textContent).join(' ').toLowerCase();
            const tags = Array.from(card.querySelectorAll('.tag')).map(tag => tag.textContent.toLowerCase()).join(' ');

            const matches = title.includes(searchTerm) ||
                           paragraphs.includes(searchTerm) ||
                           tags.includes(searchTerm);

            getToggleTarget(card).style.display = matches ? '' : 'none';
        });

        updateVisibleCount();
    });
}

function updateVisibleCount() {
    // Use cached cards or query if not available
    const cards = domCache.cards.length > 0 ? domCache.cards : document.querySelectorAll('.resource-card');
    let visibleCount = 0;

    cards.forEach(card => {
        if (getToggleTarget(card).style.display !== 'none') {
            visibleCount++;
        }
    });

    const countElement = document.getElementById('visibleCount');
    if (countElement) {
        countElement.textContent = visibleCount;
    }

    // Show/hide "no results" message
    const noResults = document.getElementById('noResults');
    if (noResults) {
        // '' would fall back to .no-results { display: none } in CSS, so be explicit.
        noResults.style.display = visibleCount === 0 ? 'block' : 'none';
    }

    // Announce to screen readers
    const announce = document.getElementById('searchAnnounce');
    if (announce) {
        announce.textContent = visibleCount === 0
            ? 'No resources match your search.'
            : 'Showing ' + visibleCount + ' resource' + (visibleCount !== 1 ? 's' : '') + '.';
    }
}

// Sticky-header offset for anchor jumps.
// The header's height varies by viewport (the nav collapses to a hamburger on
// mobile and wraps to multiple rows in a narrow band above that), so a single
// fixed CSS value can't keep linked headings clear of it everywhere. Measure
// the real height and publish it as --header-height; html { scroll-padding-top }
// consumes it. CSS holds sane fallbacks if this never runs.
function initHeaderHeightVar() {
    const header = document.querySelector('header');
    if (!header) return;
    const root = document.documentElement;
    const measure = function () {
        // Only offset when the header actually overlaps content. On mobile the
        // header is position:static (it scrolls away), so no offset is needed
        // and any would just leave dead space at the top after a jump.
        const pos = getComputedStyle(header).position;
        const sticks = pos === 'sticky' || pos === 'fixed';
        // A little breathing room so the heading isn't flush against the bar.
        const h = sticks ? Math.round(header.getBoundingClientRect().height) + 12 : 0;
        root.style.setProperty('--header-height', h + 'px');
    };
    // Measure now: the nav DOM is settled by this point and the site uses the
    // system font stack, so there's no async web-font reflow to wait on.
    measure();
    window.addEventListener('load', measure);            // belt-and-suspenders re-measure
    // Throttle resize with rAF (the page is visible while the user drags).
    let raf = 0;
    window.addEventListener('resize', function () {
        if (!raf) raf = requestAnimationFrame(function () { raf = 0; measure(); });
    }, { passive: true });
}

// Dark mode
//
// The initial stamp moved to /theme.js, which is render-blocking in <head>.
// This file is deferred, so doing it here meant a visitor whose stored choice
// differed from their OS painted the wrong theme first and flipped afterwards.
//
// Nothing here stamps data-theme for a visitor with no stored preference, and
// that is deliberate. style.css carries the dark tokens under
// `@media (prefers-color-scheme: dark) { :root:not([data-theme]) }`, so leaving
// the attribute off is what keeps the media query in control - which means an
// OS theme change with the page open now follows immediately, where the old
// code stamped `dark` once at load and froze it there until a reload.
const prefersDark = window.matchMedia('(prefers-color-scheme: dark)');

// The theme actually in effect, which is not always the attribute: with no
// attribute set, CSS is following the media query and the button has to agree.
function currentTheme() {
    const attr = document.documentElement.getAttribute('data-theme');
    if (attr === 'dark' || attr === 'light') return attr;
    return prefersDark.matches ? 'dark' : 'light';
}

function initThemeToggle() {
    // Find the toggle button (inserted via HTML)
    const toggle = document.querySelector('.theme-toggle');
    if (!toggle) return;

    updateToggleIcon(toggle);

    toggle.addEventListener('click', function () {
        const next = currentTheme() === 'dark' ? 'light' : 'dark';
        document.documentElement.setAttribute('data-theme', next);
        try {
            localStorage.setItem('theme', next);
        } catch (e) {
            /* Private mode or blocked storage: the choice holds for this page
               and simply does not persist. Not worth failing the click over. */
        }
        updateToggleIcon(this);
    });

    // While no explicit choice is stored the page tracks the OS, so the icon
    // has to track it too.
    const onSystemChange = function () {
        if (!document.documentElement.hasAttribute('data-theme')) {
            updateToggleIcon(toggle);
        }
    };
    if (prefersDark.addEventListener) {
        prefersDark.addEventListener('change', onSystemChange);
    } else if (prefersDark.addListener) {
        prefersDark.addListener(onSystemChange);
    }
}

function updateToggleIcon(btn) {
    const isDark = currentTheme() === 'dark';
    btn.textContent = isDark ? '☀️' : '🌙';
    btn.setAttribute('aria-label', isDark ? 'Switch to light mode' : 'Switch to dark mode');
}

// Search suggestions / autocomplete
function initSearchSuggestions() {
    const input = domCache.searchInput;
    if (!input) return;

    // Wrap input in search-wrapper for positioning
    const wrapper = document.createElement('div');
    wrapper.className = 'search-wrapper';
    input.parentNode.insertBefore(wrapper, input);
    wrapper.appendChild(input);

    // Create suggestions dropdown
    const dropdown = document.createElement('div');
    dropdown.className = 'search-suggestions';
    dropdown.setAttribute('role', 'listbox');
    dropdown.id = 'searchSuggestions';
    wrapper.appendChild(dropdown);

    input.setAttribute('role', 'combobox');
    input.setAttribute('aria-autocomplete', 'list');
    input.setAttribute('aria-controls', 'searchSuggestions');
    input.setAttribute('aria-expanded', 'false');

    // Build suggestion index from cards
    const suggestions = buildSuggestionIndex();
    let highlightIndex = -1;

    const debouncedSuggest = debounce(function() {
        const query = input.value.trim().toLowerCase();
        if (query.length < 2) {
            closeSuggestions();
            return;
        }

        const matches = suggestions.filter(s =>
            s.text.toLowerCase().includes(query)
        ).slice(0, 8);

        if (matches.length === 0) {
            closeSuggestions();
            return;
        }

        dropdown.innerHTML = '';
        matches.forEach((match, i) => {
            const div = document.createElement('div');
            div.className = 'search-suggestion';
            div.setAttribute('role', 'option');
            div.dataset.value = match.text;
            div.innerHTML = `<span>${sanitize(match.text)}</span><span class="suggestion-type">${sanitize(match.type)}</span>`;
            div.addEventListener('mousedown', function(e) {
                e.preventDefault();
                input.value = match.text;
                closeSuggestions();
                filterResources(match.text.toLowerCase());
            });
            dropdown.appendChild(div);
        });

        highlightIndex = -1;
        dropdown.classList.add('visible');
        input.setAttribute('aria-expanded', 'true');
    }, 100);

    input.addEventListener('input', debouncedSuggest);

    input.addEventListener('keydown', function(e) {
        const items = dropdown.querySelectorAll('.search-suggestion');
        if (!dropdown.classList.contains('visible') || items.length === 0) return;

        if (e.key === 'ArrowDown') {
            e.preventDefault();
            highlightIndex = Math.min(highlightIndex + 1, items.length - 1);
            updateHighlight(items, highlightIndex);
        } else if (e.key === 'ArrowUp') {
            e.preventDefault();
            highlightIndex = Math.max(highlightIndex - 1, 0);
            updateHighlight(items, highlightIndex);
        } else if (e.key === 'Enter' && highlightIndex >= 0) {
            e.preventDefault();
            input.value = items[highlightIndex].dataset.value;
            closeSuggestions();
            filterResources(input.value.toLowerCase());
        } else if (e.key === 'Escape') {
            closeSuggestions();
        }
    });

    input.addEventListener('blur', function() {
        setTimeout(closeSuggestions, 150);
    });

    function closeSuggestions() {
        dropdown.classList.remove('visible');
        dropdown.innerHTML = '';
        highlightIndex = -1;
        input.setAttribute('aria-expanded', 'false');
    }

    function updateHighlight(items, index) {
        items.forEach(item => item.classList.remove('highlighted'));
        if (index >= 0 && index < items.length) {
            items[index].classList.add('highlighted');
            items[index].scrollIntoView({ block: 'nearest' });
        }
    }
}

function buildSuggestionIndex() {
    const seen = new Set();
    const suggestions = [];
    const cards = document.querySelectorAll('.resource-card');

    cards.forEach(card => {
        // Add card titles
        const title = card.querySelector('h3')?.textContent.trim();
        if (title && !seen.has(title.toLowerCase())) {
            seen.add(title.toLowerCase());
            suggestions.push({ text: title, type: 'Resource' });
        }

        // Add tags
        card.querySelectorAll('.tag').forEach(tag => {
            const t = tag.textContent.trim();
            if (t && !seen.has(t.toLowerCase())) {
                seen.add(t.toLowerCase());
                suggestions.push({ text: t, type: 'Tag' });
            }
        });
    });

    return suggestions;
}

// Social sharing buttons (news page)
function initShareButtons() {
    if (!document.body.classList.contains('news-page')) return;

    document.querySelectorAll('.resource-card').forEach(card => {
        const cardLink = card.closest('.card-link');
        if (!cardLink) return;

        const url = cardLink.href;
        const title = card.querySelector('h3')?.textContent.trim() || '';
        const encodedUrl = encodeURIComponent(url);
        const encodedTitle = encodeURIComponent(title);

        const container = document.createElement('div');
        container.className = 'share-buttons';

        container.innerHTML =
            `<a href="https://www.linkedin.com/sharing/share-offsite/?url=${encodedUrl}" class="share-btn share-btn--linkedin" target="_blank" rel="noopener noreferrer" aria-label="Share on LinkedIn" title="Share on LinkedIn">in</a>` +
            `<a href="https://twitter.com/intent/tweet?url=${encodedUrl}&text=${encodedTitle}" class="share-btn share-btn--twitter" target="_blank" rel="noopener noreferrer" aria-label="Share on X" title="Share on X">X</a>` +
            `<a href="https://bsky.app/intent/compose?text=${encodedTitle}%20${encodedUrl}" class="share-btn share-btn--bluesky" target="_blank" rel="noopener noreferrer" aria-label="Share on Bluesky" title="Share on Bluesky">🦋</a>` +
            `<a href="https://www.reddit.com/submit?url=${encodedUrl}&title=${encodedTitle}" class="share-btn share-btn--reddit" target="_blank" rel="noopener noreferrer" aria-label="Share on Reddit" title="Share on Reddit">r/</a>`;

        // Prevent share button clicks from navigating the parent card-link
        container.addEventListener('click', function(e) {
            e.stopPropagation();
        });

        card.appendChild(container);
    });
}

// Resource card tooltips
function initTooltips() {
    // Skip on touch devices - no hover available
    if (window.matchMedia('(hover: none) and (pointer: coarse)').matches) return;

    var tooltip = document.createElement('div');
    tooltip.className = 'resource-tooltip';
    tooltip.setAttribute('role', 'tooltip');
    tooltip.setAttribute('aria-label', 'Resource description');
    tooltip.setAttribute('aria-hidden', 'true');
    tooltip.id = 'resourceTooltip';
    document.body.appendChild(tooltip);

    var showTimeout = null;
    var currentCard = null;

    var container = document.getElementById('main-content');
    if (!container) return;

    container.addEventListener('mouseover', function (e) {
        var card = e.target.closest('.resource-card[data-tooltip]');
        if (!card || card === currentCard) return;

        currentCard = card;
        clearTimeout(showTimeout);

        showTimeout = setTimeout(function () {
            tooltip.textContent = card.dataset.tooltip;
            card.setAttribute('aria-describedby', 'resourceTooltip');
            tooltip.setAttribute('aria-hidden', 'false');
            tooltip.classList.add('visible');
            requestAnimationFrame(function () {
                cachedTw = tooltip.offsetWidth || 360;
                cachedTh = tooltip.offsetHeight || 60;
            });
        }, 300);
    });

    var cachedTw = 360;
    var cachedTh = 60;
    container.addEventListener('mousemove', function (e) {
        if (!tooltip.classList.contains('visible') && !showTimeout) return;

        var pad = 12;
        var edge = 8;
        var tw = cachedTw;
        var th = cachedTh;

        var x = e.clientX + pad;
        var y = e.clientY + pad;

        if (x + tw > window.innerWidth - edge) x = e.clientX - tw - pad;
        if (y + th > window.innerHeight - edge) y = e.clientY - th - pad;
        x = Math.max(edge, x);
        y = Math.max(edge, y);

        tooltip.style.left = x + 'px';
        tooltip.style.top = y + 'px';
    });

    container.addEventListener('mouseout', function (e) {
        var card = e.target.closest('.resource-card[data-tooltip]');
        if (!card) return;

        var related = e.relatedTarget;
        if (related && card.contains(related)) return;

        clearTimeout(showTimeout);
        showTimeout = null;
        currentCard = null;
        tooltip.classList.remove('visible');
        tooltip.setAttribute('aria-hidden', 'true');
        card.removeAttribute('aria-describedby');
    });
}

// Add a site-wide "Search" link to the top-level header nav. Runs on every
// page that loads main.js - saves us from editing the hardcoded <nav> in
// ~30 HTML files. The link points at /search.html, where the Pagefind UI
// renders. Idempotent: if a search link already exists in the markup (e.g.
// search.html itself adds one statically in the future), the function does
// nothing.
function injectSearchLink() {
    const navUl = document.querySelector('header nav > ul');
    if (!navUl) return;
    if (navUl.querySelector('.nav-search-item')) return;

    const li = document.createElement('li');
    li.className = 'nav-search-item';

    const a = document.createElement('a');
    a.href = '/search.html';
    a.className = 'nav-search-link';
    a.setAttribute('aria-label', 'Search the site');
    // Magnifying glass + visible "Search" label so the affordance reads
    // clearly on both desktop and the mobile hamburger menu. The wrapping
    // span lets CSS shorten / hide the text on tight viewports later.
    a.innerHTML = '<span aria-hidden="true">🔍</span> <span class="nav-search-text">Search</span>';

    // If the current page IS /search.html, mark the link as the current page
    // so it gets the same styling as other active nav items.
    if (location.pathname.replace(/^\/+/, '').toLowerCase() === 'search.html') {
        a.setAttribute('aria-current', 'page');
    }

    li.appendChild(a);

    // Insert before the trailing support/CTA pair (Support, Join Friday Zoom)
    // so it lives in the primary nav region, not after the call-to-action.
    // Fall back to appending if neither is on this page.
    const tail = navUl.querySelector('.nav-coffee-item, .nav-cta-item');
    if (tail) navUl.insertBefore(li, tail);
    else navUl.appendChild(li);
}

function initDropdownNav() {
    const items = document.querySelectorAll('.has-dropdown');
    if (!items.length) return;

    const isMobile = () => window.matchMedia('(max-width: 768px)').matches;

    const closeAll = (except) => {
        items.forEach(item => {
            if (item === except) return;
            item.classList.remove('open');
            const toggle = item.querySelector('.dropdown-toggle');
            if (toggle) toggle.setAttribute('aria-expanded', 'false');
        });
    };

    items.forEach(item => {
        const toggle = item.querySelector('.dropdown-toggle');
        if (!toggle) return;

        toggle.addEventListener('click', (e) => {
            e.preventDefault();
            e.stopPropagation();
            const willOpen = !item.classList.contains('open');
            closeAll(item);
            item.classList.toggle('open', willOpen);
            toggle.setAttribute('aria-expanded', String(willOpen));
        });

        toggle.addEventListener('keydown', (e) => {
            if (e.key === 'Escape') {
                item.classList.remove('open');
                toggle.setAttribute('aria-expanded', 'false');
                toggle.focus();
            }
        });

        const menu = item.querySelector('.dropdown-menu');
        if (menu) {
            menu.addEventListener('keydown', (e) => {
                if (e.key === 'Escape') {
                    item.classList.remove('open');
                    toggle.setAttribute('aria-expanded', 'false');
                    toggle.focus();
                }
            });
        }
    });

    document.addEventListener('click', (e) => {
        if (!e.target.closest('.has-dropdown')) closeAll(null);
    });

    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape') closeAll(null);
    });
}
// Localize the weekly session time. The session is Friday 07:00-08:00
// America/Los_Angeles; csoh.ics is the source of truth for both ends.
// Three consumers:
//   [data-session-localtime] - inline "(that's X your time)" after an
//     advertised "7am PT", so members outside Pacific don't do the math.
//   [data-next-session]      - the homepage next-session banner, which needs
//     the concrete upcoming date, not just the weekly cadence.
//   [data-session-countdown] - the homepage countdown, which ticks once a
//     second and shows "live now" during the hour itself rather than a
//     six-day countdown to the following week. See resolve().
// Purely additive: without Intl - or without JS at all - the markup keeps its
// server-rendered text, and the countdown stays hidden because only the code
// below adds the --on class that reveals it.
(function () {
    var TZ = 'America/Los_Angeles';
    var DURATION_MS = 60 * 60 * 1000;   // csoh.ics: DTSTART 07:00, DTEND 08:00
    var els = document.querySelectorAll('[data-session-localtime]');
    var nextEls = document.querySelectorAll('[data-next-session]');
    var countdown = document.querySelector('[data-session-countdown]');
    if (!els.length && !nextEls.length && !countdown) return;
    if (typeof Intl === 'undefined' || !Intl.DateTimeFormat) return;

    // Offset (ms) of TZ at a given instant: local wall time minus UTC.
    function tzOffset(instant) {
        var parts = new Intl.DateTimeFormat('en-US', {
            timeZone: TZ, hour12: false,
            year: 'numeric', month: '2-digit', day: '2-digit',
            hour: '2-digit', minute: '2-digit', second: '2-digit'
        }).formatToParts(instant);
        var m = {};
        for (var i = 0; i < parts.length; i++) m[parts[i].type] = parts[i].value;
        var hour = m.hour === '24' ? '00' : m.hour;
        var asUTC = Date.UTC(+m.year, +m.month - 1, +m.day, +hour, +m.minute, +m.second);
        return asUTC - instant.getTime();
    }

    // Instant of 07:00 PT on the Pacific calendar day containing `probe`, or
    // null if that day is not a Friday. (Friday 7am is never near a DST
    // switch, so the offset at 07:00 UTC that day equals the real one.)
    function sessionOn(probe) {
        if (new Intl.DateTimeFormat('en-US', { timeZone: TZ, weekday: 'short' }).format(probe) !== 'Fri') return null;
        var ymd = new Intl.DateTimeFormat('en-CA', {
            timeZone: TZ, year: 'numeric', month: '2-digit', day: '2-digit'
        }).format(probe).split('-');
        var naiveUTC = Date.UTC(+ymd[0], +ymd[1] - 1, +ymd[2], 7, 0, 0);
        return new Date(naiveUTC - tzOffset(new Date(naiveUTC)));
    }

    // The session worth talking about: the one under way, else the next to
    // start. The in-progress case is the whole reason this isn't just "next
    // start" - at 07:30 on a Friday the next start is six days out, and a
    // banner counting down to next week while people are in the room is the
    // one moment this component must not get wrong.
    function resolve(nowMs) {
        for (var d = 0; d < 8; d++) {
            var start = sessionOn(new Date(nowMs + d * 86400000));
            if (!start) continue;
            var t = start.getTime();
            if (nowMs < t) return { live: false, start: start };
            if (nowMs < t + DURATION_MS) return { live: true, start: start };
        }
        return null;
    }

    var state = resolve(Date.now());
    if (!state) return;

    var viewerTZ = '';
    try { viewerTZ = Intl.DateTimeFormat().resolvedOptions().timeZone || ''; } catch (e) {}
    var isPacific = viewerTZ === TZ;

    // Banner: name the actual upcoming date, then the viewer's local clock
    // time. Re-rendered on a state flip so a page left open across 07:00
    // stops advertising a session that has already started.
    function renderBanner() {
        if (!nextEls.length) return;
        var when;
        if (state.live) {
            when = 'Happening now - 7:00 to 8:00 AM PT';
        } else {
            when = new Intl.DateTimeFormat('en-US', {
                timeZone: TZ, weekday: 'long', month: 'long', day: 'numeric'
            }).format(state.start) + ' at 7:00 AM PT';
            if (!isPacific) {
                when += ' · ' + new Intl.DateTimeFormat(undefined, {
                    hour: 'numeric', minute: '2-digit', timeZoneName: 'short'
                }).format(state.start) + ' your time';
            }
        }
        for (var k = 0; k < nextEls.length; k++) nextEls[k].textContent = when;
    }
    renderBanner();

    if (countdown) (function () {
        var UNITS = ['days', 'hours', 'minutes', 'seconds'];
        var wrap = {}, num = {}, label = {};
        for (var u = 0; u < UNITS.length; u++) {
            var n = UNITS[u];
            wrap[n] = countdown.querySelector('[data-unit="' + n + '"]');
            num[n] = wrap[n] && wrap[n].querySelector('.next-session__unit-num');
            label[n] = wrap[n] && wrap[n].querySelector('.next-session__unit-label');
            if (!num[n] || !label[n]) return;   // markup changed - leave it hidden
        }

        function set(el, text) { if (el.textContent !== text) el.textContent = text; }

        function paint(nowMs) {
            countdown.classList.toggle('next-session__countdown--live', state.live);
            if (state.live) return;
            var secs = Math.floor(Math.max(0, state.start.getTime() - nowMs) / 1000);
            var value = {
                days: Math.floor(secs / 86400),
                hours: Math.floor(secs % 86400 / 3600),
                minutes: Math.floor(secs % 3600 / 60),
                seconds: secs % 60
            };
            // Drop the days tile rather than show "0 days" on the last day:
            // a zeroed leading unit reads as broken, not as "soon".
            wrap.days.hidden = value.days === 0;
            for (var i = 0; i < UNITS.length; i++) {
                var n = UNITS[i];
                set(num[n], n === 'days' || value[n] > 9 ? String(value[n]) : '0' + value[n]);
                set(label[n], value[n] === 1 ? n.slice(0, -1) : n);
            }
        }

        // Recompute from the clock every tick rather than decrementing a
        // counter: background tabs throttle timers, and a machine that sleeps
        // for an hour must wake up showing the truth, not an hour of drift.
        function tick() {
            var nowMs = Date.now();
            if (nowMs >= state.start.getTime() + (state.live ? DURATION_MS : 0)) {
                var next = resolve(nowMs);
                if (next) {
                    state = next;
                    renderBanner();
                }
            }
            paint(nowMs);
        }

        paint(Date.now());
        countdown.classList.add('next-session__countdown--on');
        setInterval(tick, 1000);
    })();

    if (!els.length || isPacific) return; // already Pacific - nothing to add
    var local = new Intl.DateTimeFormat(undefined, {
        weekday: 'long', hour: 'numeric', minute: '2-digit', timeZoneName: 'short'
    }).format(state.start);
    for (var j = 0; j < els.length; j++) {
        els[j].textContent = ' (that’s ' + local + ' your time)';
    }
})();
